### Iniciar o Chamado 1
PATCH http://localhost:5144/api/Chamado/1/iniciar

### Encerrar o Chamado 1
PATCH http://localhost:5144/api/Chamado/1/encerrar
Content-Type: application/json

### Criar um comentário no Chamado 1
POST http://localhost:5144/api/Interacao
Content-Type: application/json

{
  "chamadoId": 1,
  "quemEscreveu": "João Técnico",
  "mensagem": "Iniciando a substituição da fonte de alimentação."
}